Repository vladstanescu94/ProiectIS, pull requests merged in 2018-12, with the labels that each got.

#14 Add modal login
  ProiectIS-war/web/Static/build/css/main.css
  ProiectIS-war/web/Static/build/css/main.css.map
  ProiectIS-war/web/Static/build/css/main.min.css
  ProiectIS-war/web/Static/index.html
  ProiectIS-war/web/Static/src/stylus/main.styl
  ProiectIS-war/web/Static/src/stylus/modules/login.styl
  ProiectIS-war/web/Static/src/stylus/modules/navigation.styl
Labels: Review

#19 Remove ids and sale page
  package-lock.json
  src/main/resources/static/build/js/main.js
  src/main/resources/static/build/js/sale.js
  src/main/resources/static/index.html
  src/main/resources/static/sale.html
  src/main/resources/static/src/dashboard.html
Labels: Review

#21 migrated to MYSQL
  pom.xml
  src/main/resources/application.properties
Labels: Ready to Merge

#23 Feature/authenthication
  pom.xml
  src/main/java/com/proiect/pos/Config/WebSecurityConfig.java
  src/main/java/com/proiect/pos/Controllers/ProjectController.java
  src/main/java/com/proiect/pos/Controllers/RestProjectController.java
  src/main/java/com/proiect/pos/Entities/Coupon.java
  src/main/java/com/proiect/pos/Entities/Invoice.java
  src/main/java/com/proiect/pos/Entities/InvoiceItems.java
  src/main/java/com/proiect/pos/Entities/InvoiceItemsPK.java
  src/main/java/com/proiect/pos/Entities/Product.java
  src/main/java/com/proiect/pos/Entities/Seller.java
  src/main/java/com/proiect/pos/OLD/Coupon.java
  src/main/java/com/proiect/pos/OLD/Invoice.java
  src/main/java/com/proiect/pos/OLD/InvoiceItems.java
  src/main/java/com/proiect/pos/OLD/InvoiceItemsPK.java
  src/main/java/com/proiect/pos/OLD/Product.java
  src/main/java/com/proiect/pos/OLD/Seller.java
  src/main/java/com/proiect/pos/PosApplication.java
  src/main/java/com/proiect/pos/Repositories/ProductRepository.java
  src/main/java/com/proiect/pos/config/WebMvcConfig.java
  src/main/java/com/proiect/pos/config/WebSecurityConfig.java
  src/main/java/com/proiect/pos/model/Role.java
  src/main/java/com/proiect/pos/model/Seller.java
  src/main/java/com/proiect/pos/repository/ProductRepository.java
  src/main/java/com/proiect/pos/repository/RoleRepository.java
  src/main/java/com/proiect/pos/repository/SellerRepository.java
  src/main/java/com/proiect/pos/service/SellerService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/templates/admin/test.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
Labels: Ready to Merge

#29 Feature/templating
  src/main/java/com/proiect/pos/Controllers/RestProjectController.java
  src/main/java/com/proiect/pos/config/WebMvcConfig.java
  src/main/java/com/proiect/pos/config/WebSecurityConfig.java
  src/main/java/com/proiect/pos/controller/AdminController.java
  src/main/java/com/proiect/pos/controller/ProjectController.java
  src/main/java/com/proiect/pos/controller/RestProjectController.java
  src/main/java/com/proiect/pos/controller/SaleController.java
  src/main/java/com/proiect/pos/model/Product.java
  src/main/java/com/proiect/pos/repository/ProductRepository.java
  src/main/java/com/proiect/pos/service/ProductService.java
  src/main/java/com/proiect/pos/service/SellerService.java
  src/main/resources/static/build/js/sale.js
  src/main/resources/templates/admin/addproduct.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/fragments/productItem.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/sale.html
Labels: Ready to Merge

#31 Feature/template refactoring
  src/main/java/com/proiect/pos/config/WebSecurityConfig.java
  src/main/java/com/proiect/pos/controller/ProjectController.java
  src/main/resources/static/build/css/main.css
  src/main/resources/static/build/css/main.css.map
  src/main/resources/static/build/css/main.min.css
  src/main/resources/static/build/js/main.js
  src/main/resources/static/src/stylus/common/defaults.styl
  src/main/resources/static/src/stylus/modules/login.styl
  src/main/resources/templates/admin/addproduct.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/head.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/fragments/productItem.html
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
  src/main/resources/templates/sale.html
Labels: Review

#32 Hotfix/25
  .gitignore
  pom.xml
  src/main/java/com/proiect/pos/PosApplication.java
  src/main/java/com/proiect/pos/config/WebMvcConfig.java
  src/main/java/com/proiect/pos/controller/rest/FileController.java
  src/main/java/com/proiect/pos/controller/rest/ProductController.java
  src/main/java/com/proiect/pos/model/Product.java
  src/main/java/com/proiect/pos/service/ProductService.java
  src/main/resources/application.properties
  src/main/resources/static/build/js/addProduct.js
  src/main/resources/static/build/js/sale.js
  src/main/resources/templates/admin/addproduct.html
Labels: Ready to Merge, Review

#36 Add product image padding #35
  src/main/resources/static/build/css/main.css
  src/main/resources/static/build/css/main.css.map
  src/main/resources/static/build/css/main.min.css
  src/main/resources/static/src/stylus/modules/products.styl
Labels: Ready to Merge

#37 Implemented migration for the database
  pom.xml
  src/main/java/com/proiect/pos/model/Product.java
  src/main/java/com/proiect/pos/model/Role.java
  src/main/java/com/proiect/pos/model/Seller.java
  src/main/resources/application.properties
  src/main/resources/db/changeLog/01-create-product-role-and-seller-schema.xml
  src/main/resources/db/changeLog/02-insert-dummy-values.xml
  src/main/resources/db/data.sql
  src/main/resources/db/liquibase-changeLog.xml
  src/main/resources/liquibase.properties
Labels: Ready to Merge

#43 Add keypad function to input numbers.
  src/main/resources/static/build/js/keypad.js
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/sale.html
Labels: Review

#39 Hotfix/Product-list
  src/main/resources/static/build/css/main.css
  src/main/resources/static/build/css/main.css.map
  src/main/resources/static/build/css/main.min.css
  src/main/resources/static/src/assets/images/default_user.jpg
  src/main/resources/static/src/stylus/modules/login.styl
  src/main/resources/static/src/stylus/modules/navigation.styl
  src/main/resources/static/src/stylus/modules/products.styl
  src/main/resources/templates/fragments/navbar.html
Labels: Ready to Merge, Review

#40 Feature/add product form
  src/main/resources/static/build/css/main.css
  src/main/resources/static/build/css/main.css.map
  src/main/resources/static/build/css/main.min.css
  src/main/resources/static/src/stylus/common/defaults.styl
  src/main/resources/static/src/stylus/main.styl
  src/main/resources/static/src/stylus/modules/form-add-product.styl
  src/main/resources/static/src/stylus/modules/products.styl
  src/main/resources/templates/admin/addproduct.html
Labels: Review
