Repository vladstanescu94/ProiectIS, pull requests merged in 2019-01, with the labels that each got.

#62 Feature/#47
  src/main/java/com/proiect/pos/controller/MainController.java
  src/main/java/com/proiect/pos/controller/rest/InvoiceController.java
  src/main/java/com/proiect/pos/controller/rest/ProductController.java
  src/main/java/com/proiect/pos/model/Coupon.java
  src/main/java/com/proiect/pos/model/Invoice.java
  src/main/java/com/proiect/pos/model/InvoiceItem.java
  src/main/java/com/proiect/pos/model/Product.java
  src/main/java/com/proiect/pos/model/Seller.java
  src/main/java/com/proiect/pos/repository/CouponRepository.java
  src/main/java/com/proiect/pos/repository/InvoiceRepository.java
  src/main/java/com/proiect/pos/service/CouponService.java
  src/main/java/com/proiect/pos/service/InvoiceService.java
  src/main/resources/db/changeLog/03-create-coupon-schema.xml
  src/main/resources/db/changeLog/04-create-invoice-related-schemas.xml
  src/main/resources/db/liquibase-changeLog.xml
  src/main/resources/static/build/js/sale.js
  src/main/resources/templates/checkout.html
  src/main/resources/templates/sale.html
Labels: Ready to Merge

#54 Change /admin/addproduct to /dashboard
  src/main/java/com/proiect/pos/controller/AdminController.java
  src/main/java/com/proiect/pos/controller/MainController.java
  src/main/resources/templates/admin/addproduct.html
  src/main/resources/templates/dashboard.html
  src/main/resources/templates/fragments/navbar.html
Labels: Review

#67 Price displays only 2 decimal
  src/main/resources/static/build/js/sale.js
Labels: Ready to Merge, Review

#74 Add changeLog for dummy coupons.
  src/main/resources/db/changeLog/02-insert-dummy-values.xml
  src/main/resources/db/changeLog/05-insert-dummy-coupons.xml
  src/main/resources/db/liquibase-changeLog.xml
Labels: Review
